### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by Nefari0uss** [OSUOSC/resources#5]
I know this is somewhat petty but I'm not a big fan of this current format of 

`awesome resource https://awesome.resource/blah/blah.pdf`

Since @moore3071 doesn't like having it be a traditional link (discussed [here](https://github.com/OSUOSC/resources/commit/1ab56f20b08a4b029c277671d18e88e366913e63)) such as [sample](.), might I suggest this:

* Open Source Club at Ohio State: [osu.edu](https://www.opensource.osu.edu)

Or even this:
* Open Source Club at Ohio State: [opensource.osu.edu](https://www.opensource.osu.edu)

I believe the latter two are significantly cleaner while still maintaining "better attribution". Thoughts?

**Comment by moore3071** [comment]
I would be perfectly okay with either of those two proposed formats.

**Comment by smacz42** [comment]
If I may suggest an alternative, it is quite popular on github to curate what's known as an "awesome-list"

* https://github.com/vinta/awesome-python
* https://github.com/n1trux/awesome-sysadmin
* https://github.com/Kickball/awesome-selfhosted

This has the advantage of a ToC followed by the actual content. This makes compiling into another format such as one that would be suitable for web documentation feasible. (See https://awesome-python.com/)

**Comment by Nefari0uss** [comment]
I'm not against the `Awesome List` format.

**Comment by smacz42** [comment]
@Nefari0uss @moore3071 This is what it would look like as an awesome-list

https://github.com/smacz42/resources/tree/awesomeize

**Comment by Nefari0uss** [comment]
@smacz42 If you make it a pull request, I'd be willing to approve it (assuming @moore3071 approves as well).

**Comment by Nefari0uss** [comment]
This issue has been resolved as of #7.
